### ISSUE TITLE
CUDA out of memory | batch size = 1

### ISSUE THREAD

**Issue by forkbabu** [LS4GAN/uvcgan#2]
![image](https://user-images.githubusercontent.com/8037297/161391157-60d158a7-51f8-4b62-86f5-6769fe942957.png)

**Comment by forkbabu** [comment]
@usert5432

**Comment by YHRen** [comment]
@forkbabu what is your GPU memory? (we have tested with a 48GB GPU)

**Comment by forkbabu** [comment]
24gb nvidia titan rtx

**Comment by usert5432** [comment]
Hi @forkbabu, thanks for reporting this issue.

According to my benchmarks, it takes about 2.5 GiB to train a BERT-like model and about 6 GiB to train a CycleGAN model with batch_size = 1, so your GPU should have enough memory. To better troubleshoot this issue, would it be possible for you to provide the command that you use to run the training and the training output?

**Comment by forkbabu** [comment]
```
python scripts/train/selfie2anime/bert_selfie2anime-256.py
```

**Comment by usert5432** [comment]
Hi @forkbabu,

Judging by the training log, it looks like the training is using `batch_size = 64`. Could you try running it with a smaller batch size? For example:
```
python scripts/train/selfie2anime/bert_selfie2anime-256.py --batch-size 16
```

If you have tried running this training with `batch_size = 64` previously, then the command above should immediately fail due to a fail-safe that prevents saving two different trainings into the same output directory. You will see an error message like this:
```
RuntimeError: Config collision detected in '<PATH_TO_MODEL>'...
--- Old Config

+++ New Config

@@ -1,5 +1,5 @@

 {
-    "batch_size": 64,
+    "batch_size": 16,
     "data": {
         "dataset": "cyclegan",
         "dataset_args": {

```

If you see this message, then everything is fine. Simply remove the directory indicated in the error message `PATH_TO_MODEL`, and try running the training again with `--batch-size 16`. I expect 24GiB should be enough for `batch-size = 16`.

**Comment by forkbabu** [comment]
@usert5432 thanks it worked.!
